referenceGenome: "./data/hg38.fa"

# Embedding generation
batchInference:
  batchSize: 5000
  workers: 8
  bufferSize: 10000
  inputsInMemory: True
  rowsLimit: null
  maxSeqLen: 100
  preferModel: 'hyenaDNA'

dataDir: 'data'
experimentsDir: 'experiments'
