#!/bin/bash

function sync_remote {
    rsync -iva --delete . fijicluster:projects/giggle-ml \
        --filter='- data/' \
        --filter='- .data/' \
        --filter='- .git/' \
        --filter='- .direnv/' \
        --filter='- .venv/' \
        --filter='- .snakemake/' \
        --filter='- .pytest_cache/' \
        --filter='- */__pycache__/' \
        --prune-empty-dirs
}

sync_remote
export -f sync_remote
fswatch -ro . | xargs -n1 -I{} bash -c 'sync_remote >> /dev/null && echo "synced ($(date +%T))"'
echo "...watching"
